parkingsystem/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('overview/', views.parking, name='parking'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name ='profile-update'),
    path('profile/<int:pk>', views.ProfileDetailView.as_view(), name='home'),
    path('signup/', views.signup, name='signup'),
]
#  path('home', views.home, name='home'),

#Parkinglots
urlpatterns += [
    path('parkinglots/', views.ParkingLotListView.as_view(), name='parkinglots'),
    path('parkinglot/<int:pk>', views.ParkingLotDetailView.as_view(), name='parkinglot-detail'),
    path('parkinglot/add/', views.ParkingLotCreate.as_view(), name='parkinglot-add'),
    path('parkinglot/<int:pk>/ticket/', views.plticket, name='plticket'),
]

#Parkingspaces
urlpatterns += [
    path('parkinglot/parkingspace/<int:pk>', views.ParkingSpaceDetailView.as_view(), name='parkingspace-detail'),
    path('standaloneparking/add/', views.StandaloneParkingSpaceCreate.as_view(), name='standalone-add'),
    path('standaloneparking/<int:pk>/update/', views.StandaloneParkingSpaceUpdate.as_view(), name='standalone-update'),
    path('standaloneparking/<int:pk>/delete/', views.StandaloneParkingSpaceDelete.as_view(), name='standalone-delete'),
    path('standaloneparking/<int:pk>', views.StandaloneParkingSpaceDetailView.as_view(), name='standalone-detail'),
    path('standaloneparking/<int:pk>/ticket/', views.psticket, name='psticket'),
]

#Vehicles
urlpatterns += [
    path('vehicles/', views.VehicleListView.as_view(), name='vehicles'),
    path('vehicle/<int:pk>/', views.VehicleDetailView.as_view(), name='vehicle-detail'),
    path('vehicle/add/', views.VehicleCreate.as_view(), name='vehicle-add'),
    path('vehicle/<int:pk>/update/', views.VehicleUpdate.as_view(), name='vehicle-update'),
    path('vehicle/<int:pk>/delete', views.VehicleDelete.as_view(), name='vehicle-delete')
]

#UserOwnedParkingSpace
urlpatterns += [
    path('myparkingspace/<int:pk>/', views.UserOwnedParkingDetailView.as_view(), name='userparking-detail'),
    path('myparkingspace/add/', views.UserOwnedParkingCreate.as_view(), name='userparking-add'),
    path('myparkingspace/<int:pk>/update/', views.UserOwnedParkingUpdate.as_view(), name='userparking-update'),
    path('myparkingspace/<int:pk>/delete/', views.UserOwnedParkingDelete.as_view(), name='userparking-delete'),
]

#Tickets (for users. Can only see their own tickets)
urlpatterns += [
    path('tickets/', views.TicketListView.as_view(), name='tickets'),
    path('ticket/<int:pk>/', views.TicketDetailView.as_view(), name='ticket-detail'),
    path('ticket/add/', views.ticket, name='ticket-add'),
    path('ticket/<int:pk>/update/', views.TicketUpdate.as_view(), name='ticket-update'),
    path('ticket/<int:pk>/terminate', views.terminate_ticket, name='ticket-terminate'),
    path('ajax/load-parkingspaces/', views.load_parkingspace, name='ajax-load-parkingspace'),
    path('ajax/load-vehicles/', views.load_vehicles, name='ajax-load-vehicle'),
    path('ajax/load-pl-price/', views.load_pl_price, name='ajax-load-pl-price'),
    path('ajax/load-ps-price/', views.load_ps_price, name='ajax-load-ps-price'),
]

#Need a listview for staff which can see all the tickets.

smartpark/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from parkingsystem import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('parking/', include('parkingsystem.urls')),
    path('', RedirectView.as_view(url='/parking')),
    path('accounts/', include('django.contrib.auth.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

parkingsystem/models.py
from django.db import models
import uuid # required for unique parkingspace
from django.contrib.auth.models import User, Permission

#for post save when creating a parking lot:
from django.db.models.signals import post_save
from django.dispatch import receiver

#to generate urls
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=150, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.PositiveIntegerField(blank=True, null=True)
    birthdate = models.DateField(blank=True, null=True)
    
    #TODO: DEL
    total_income = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.user.__str__()

    def get_absolute_url(self):
        return reverse('home', args=[str(self.id)])

    def profit(self, amount):
        self.total_income += amount

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

#TODO: Kan slettes
class ParkingSpaceType(models.Model):
    """
    Model representing a type of parkingspace(e.g. Car, motorbike, etc)
    """
    parking_type = models.CharField(max_length=150, unique=True)
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.parking_type

class ParkingLot(models.Model):
    """
    Model representing a parking lot which can have mant parkingspaces
    """
    #ID field added automatically
    #TODO: add mb_space_taken and add it into maps.
    name = models.CharField(max_length=150, null=True, blank=True)
    price = models.PositiveIntegerField()
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    rfid = models.PositiveIntegerField()
    capacity_car = models.PositiveIntegerField()
    capacity_motorbike = models.PositiveIntegerField()
    car_space_taken = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('parkinglot-detail', args=[str(self.id)])

    @property
    def car_taken(self):
        return ParkingSpace.objects.filter(parking_lot=self, parking_type='c', status='t').count()
    
    @property
    def mb_taken(self):
        return ParkingSpace.objects.filter(parking_lot=self, parking_type='m', status='t').count()

class ParkingSpaceManager(models.Manager):
    def get_avail_parking(self):
        return self.filter(status='a')

class ParkingSpace(models.Model):
    TYPES = (
        ('c', 'Car'),
        ('m', 'Motorbike'),
    ) 
    parking_type = models.CharField(max_length=1, choices=TYPES, null=True)
    parking_lot = models.ForeignKey(ParkingLot, on_delete=models.CASCADE, null=True, blank=True)
    taken_to = models.DateTimeField(auto_now_add=True)

    STATUS = (
        ('t', 'Taken'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    #TODO: Delete status/ change the use to property is_available.
    status = models.CharField(max_length=1, choices=STATUS, blank=True, default='a', help_text='Parking space availability')

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return str(self.id)

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this parking space.
        """
        return reverse('parkingspace-detail', args=[str(self.id)])

    def set_status(self,status):
        if (status == 't' or status == 'a' or status == 'r'):
            self.status = status
            self.save()
        return

    def set_taken_by(self, person):
        self.taken_by = person
        self.save()

    def set_taken_to(self, dateTime):
        self.taken_to = dateTime
        self.save()

    @property
    def is_available(self):
        if self.taken_to and timezone.now() > self.taken_to:
            self.set_status('a')
            return True
        return False

class StandaloneParkingSpace(ParkingSpace):
    """
    Subclass of parkingspace representing a parking space outside a parkingLot
    """
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    price = models.PositiveIntegerField()
    opening_time = models.TimeField()
    closing_time = models.TimeField()

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this parking space.
        """
        return reverse('standalone-detail', args=[str(self.id)])

class UserOwnedParking(StandaloneParkingSpace):
    """
    A standalone parking space which can be owned by an user to rent out.
    """
    owner = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.owner.__str__() +" parking")
       
    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this parking space.
        """
        return reverse('userparking-detail', args=[str(self.id)])

class Vehicle(models.Model):
    registration_number = models.CharField(max_length=50, unique=True)
    brand = models.CharField(max_length=150)
    model = models.CharField(max_length=150)
    car = models.BooleanField()
    motorbike = models.BooleanField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.registration_number

    def get_absolute_url(self):
        return reverse('vehicle-detail', args=[str(self.id)])

class Ticket(models.Model):
    start = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateTimeField()
    # On_delete Gjøres noe med før deployment??
    parking_space = models.ForeignKey(ParkingSpace, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    person = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.vehicle.owner.__str__()

    def get_absolute_url(self):
        return reverse('ticket-detail', args=[str(self.id)])

    @property
    def is_valid(self):
        if self.valid_to and timezone.now() < self.valid_to:
            self.parking_space.set_status("a")
            return True
        return False

    @property
    def duration_in_minutes(self):
        duration = self.valid_to - self.start
        return int(duration.seconds/60)

    #TODO: slettes?
    @property
    def price(self):
        try:
            price = self.parking_space.parking_lot.price * self.duration_in_minutes
        except AttributeError:
            return 0
        return int(price)

"""
Function to create parkingspaces when creating a parking lot. Uses a post_save signal on parking lot.
"""
def create_parking_space_for_parking_lot(sender, instance, **kwargs):
    if kwargs['created']:
        for x in range(0,instance.capacity_car):
            parking_space = ParkingSpace.objects.create(parking_type = 'c', parking_lot=instance)
        for y in range(0, instance.capacity_motorbike):
            parking_space = ParkingSpace.objects.create(parking_type = 'm', parking_lot=instance)

post_save.connect(create_parking_space_for_parking_lot, sender=ParkingLot)

parkingsystem/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Vehicle, Ticket, ParkingSpace, ParkingLot
from django.contrib.admin.widgets import AdminDateWidget

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('birthdate', 'mobile_number', 'address', 'city', 'zip_code')

class ParkingSpaceForm(forms.ModelForm):
    class Meta:
        model = ParkingSpace
        fields = ('parking_lot',)

class TicketForm(forms.Form):
    parkinglot  = forms.ModelChoiceField(queryset=ParkingLot.objects.all())
    parkingspace = forms.ModelChoiceField(queryset=ParkingSpace.objects.all())
    vehicle = forms.ModelChoiceField(queryset=Vehicle.objects.all())
    valid_to = forms.DateTimeField(widget = AdminDateWidget) # change widget

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        #If no parkinglot -> show only standalone parkingspaces.
        self.fields['parkingspace'].queryset = ParkingSpace.objects.filter(parking_lot=None, status='a')

        if 'parkinglot' in self.data:
            try:
                parkinglot_id = int(self.data.get('parkinglot'))
                self.fields['parkingspace'].queryset = ParkingSpace.objects.filter(parking_lot=parkinglot_id)
            except (ValueError, TypeError):
                pass

class ParkingSpaceTicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['vehicle', 'valid_to']

parkingsystem/templates/parkingsystem/custom_ticketform.html
{% extends "base.html" %}


{% load static %}
{% block javascript %}
<script src="{% static 'js/ticket/ticket.js' %}"></script>
<script src="{% static 'js/ticket/dropdown.js' %}"></script>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script src="{% static 'js/ticket/paypalbutton.js' %}"></script>

{% endblock %}


{% block content %}
<h1>New ticket </h1>
{% if user.is_authenticated %}

{% load widget_tweaks %}
<div>
    <p id='psPrice'> Price per hour: {{parkingspace.price}} </p>
</div>
<form method="post" id="TicketForm" data-parkingspace-price-url="{% url 'ajax-load-ps-price' %}" data-parkinglot-price-url="{% url 'ajax-load-pl-price' %}" data-parkingspaces-url="{% url 'ajax-load-parkingspace' %}" data-vehicles-url="{% url 'ajax-load-vehicle' %}"  novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
        <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                {{ error }}
                </div>
            {% endfor %}
            {% else %}
            {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
  {% endfor %}
    <div>
        <p>Price per hour: </p>
        <p id="ticket-price"></p>
    </div>
    <div id="paypal-button"></div>

</form>
{% endif %}
{% endblock %}

parkingsystem/templates/parkingsystem/parkinglot_form.html
{% extends "base.html" %}

{% block content %}
{% if user.is_staff %}
<h1>Add parkinglot</h1>

<form  action="" method="post">
        {% csrf_token %}
        {% include 'bootstrap-form.html' with form=form %}
        <button type="submit" class="btn btn-primary">Save</button>
    
</form>
{% endif %}
{% endblock %}

parkingsystem/templates/parkingsystem/parkinglot_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Parking lot List</h1>
    {% if user.is_authenticated %}

    {% if parkinglot_list %}
    <ul>
      {% for parkinglot in parkinglot_list %}
      <li>
        <a href="{{ parkinglot.get_absolute_url }}">{{ parkinglot.name }}</a> ({{parkinglot.latitude}})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no parkinglots in the system.</p>
    {% endif %}

    {% if standaloneparkingspace_list %}
    <ul>
      {% for standaloneparkingspace in standaloneparkingspace_list %}
      <li>hei</li>
      {% endfor %}
    </ul>
    {% endif %}

    {% else %}
    <p>You need to <a href="{% url 'login' %}">login</a> to see this</p>
    {% endif %}  
    
    {% if user.is_staff %}
    <a href="{% url 'parkinglot-add' %}"> Create a new parkinglot </a> <br>
    <a href="{% url 'standalone-add' %}"> Create a new standalone parkingspace</a>
    {% endif %}
{% endblock %}

parkingsystem/templates/parkingsystem/parkingspace_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ parkingspace.id }}</h1>



{% endblock %}

parkingsystem/templates/parkingsystem/parkingspace_dropdown.html
<option value="">---------</option>
{% for parkingspace in parkingspaces %}
<option value="{{ parkingspace.pk }}">{{ parkingspace.id }}</option>
{% endfor %}

parkingsystem/templates/parkingsystem/profile.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
    
    <div class="col profile">
        <h1>Profile</h1>

        <p class="profileText">{{user.username}}</p>

        <p>{{user.first_name}}</p>
        <p>{{user.last_name}}</p>
        <p>{{user.profile.birthdate}}</p>
        <p>{{user.email}}</p>
        <p>{{user.profile.mobile_number}}</p>
        <p>{{user.profile.address}}</p>
        <p>{{user.profile.city}}</p>
        <p>{{user.profile.zip_code}}</p>
    </div>
</div>



    <p><a href="{% url 'profile-update' user.profile.id %}">Update profile</a></p>


{% endif %}
{% endblock %}

parkingsystem/templates/parkingsystem/profile_form.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
<h1>Hello {{user.username}}</h1>

<form  action="" method="post">
    {% csrf_token %}
    {% include 'bootstrap-form.html' with form=form %}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

{% endif %}
{% endblock %}

parkingsystem/templates/parkingsystem/standaloneparkingspace_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ standaloneparkingspace.id }}</h1>

  <a href="{% url 'standalone-update' standaloneparkingspace.id %}"> Update parkingspace</a>
  <a href="{% url 'standalone-delete' standaloneparkingspace.id %}"> Remove parkingspace </a>


  <h3>Map</h3>
  <!--The div element for the map -->
  <div id="map"></div>
    <script>
  
  // Initialize and add the map
    function initMap() {
// The location of Uluru
    
    var num1 = parseFloat("{{standaloneparkingspace.latitude}} ")
    var num2 = parseFloat("{{standaloneparkingspace.longitude}}")
    var status = "{{ standaloneparkingspace.status }}";

    var pos = {lat: num1, lng: num2};
// The map, centered at pos
    var map = new google.maps.Map(document.getElementById('map'), {zoom: 16, center: pos});
// The marker, positioned at pos
    var marker = new google.maps.Marker({position: pos, map: map});

    var infowindow = new google.maps.InfoWindow();

     google.maps.event.addListener(marker, 'click', (function(marker){
                return function() {
                    
                    if (status == 'a') {
                        infowindow.setContent("<p> Open: {{ standaloneparkingspace.opening_time }}  - {{ standaloneparkingspace.closing_time }}<br />" +
                        "Price per hour: {{ standaloneparkingspace.price }}<br/>" +
                        "Status: {{ standaloneparkingspace.status }}<br/>" +
                        "<a href='{% url 'psticket' standaloneparkingspace.id %}'> Buy ticket </a>" +
                        "</p>");
                    } else {
                        infowindow.setContent("<p> Open: {{ standaloneparkingspace.opening_time }}  - {{ standaloneparkingspace.closing_time }}<br />" +
                        "Price per hour: {{ standaloneparkingspace.price }}<br/>" +
                        "Status: {{ standaloneparkingspace.status }}<br/>" +
                        "</p>");
                    }
                    
                    infowindow.open(map, marker);
                }
            })(marker));
    }






</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAbm5_fhoMiS2KutHvxdZlTbSf_rpxYcs&callback=initMap">
  </script>


{% endblock %}

parkingsystem/templates/parkingsystem/standaloneparkingspace_form.html
{% extends "base.html" %}

{% block content %}
{% if user.is_staff %}
<h1>Add parkingspace</h1>

<form  action="" method="post">
    {% csrf_token %}
    {% include 'bootstrap-form.html' with form=form %}
    <button type="submit" class="btn btn-primary">Save</button>

</form>

{% endif %}
{% endblock %}

parkingsystem/templates/parkingsystem/ticket_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Ticket List</h1>
    {% if user.is_authenticated %}

    {% if ticket_list %}
    <ul>
    {% for ticket in user.ticket_set.all %}
      <li>
        <a href="{{ ticket.get_absolute_url }}">{{ ticket.id }}</a> 
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>You have no parking tickets.</p>
    {% endif %}
    <a href="{% url 'ticket-add' %}">Buy a new ticket</a>
    {% else %}
    <p>You need to <a href="{% url 'login' %}">login</a> to see this</p>
    {% endif %}       
{% endblock %}

parkingsystem/templates/parkingsystem/userownedparking_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete parkingspace</h1>

<form  action="{% url 'userparking-delete' userownedparking.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>

</form>

{% endblock %}

parkingsystem/templates/parkingsystem/vehicle_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="row">
        <div class="col">
            <h3>Delete vehicle {{vehicle.registration_number}}</h3>

            <form  action="{% url 'vehicle-delete' vehicle.id %}" method="post">
                {% csrf_token %}
                {% include 'bootstrap-form.html' with form=form %}
                    <button type="submit" class="btn btn-primary">Delete</button>

            </form>

        </div>
    </div>

{% endblock %}

parkingsystem/templates/parkingsystem/vehicle_dropdown.html
<option value="">---------</option>
{% for vehicle in vehicles %}
<option value="{{ vehicle.pk }}">{{ vehicle.registration_number }}</option>
{% endfor %}

parkingsystem/templates/parkingsystem/vehicle_list.html
{% extends "base.html" %}

{% block content %}
    <h1 id="h1-vehicle"></h1>
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-10">
            <h1 id="h1-vehicle">My vehicles </h1>
        </div>
        <div class="col-2">
            <a href="{% url 'vehicle-add' %}"> 
                <div>
                    <i class="fa fa-plus fa-2x adder-h1"></i>
                </div>  
            </a>
        </div>
    </div>

    {% if vehicle_list %}
    <div class="row">
        {% for vehicle in user.vehicle_set.all %}
            <div class="col-4">
                {% if vehicle.car %}
                <a href="{{ vehicle.get_absolute_url }}">
                    <div class="index-vehicle">
                        <i class="fa fa-car fa-3x"></i>
                        <p>{{ vehicle.registration_number }}</p>
                    </div>
                </a>
                {% elif vehicle.motorbike %}
                <a href="{{ vehicle.get_absolute_url }}">
                    <div class="index-vehicle">
                        <i class="fa fa-motorcycle fa-3x"></i>
                        <p>{{ vehicle.registration_number }}</p>
                    </div>
                </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    {% else %}
      <p>There are no vehicles in the system.</p>
    {% endif %}
    {% else %}
    <p>You need to <a href="{% url 'login' %}">login</a> to see this</p>
    {% endif %}       
{% endblock %}